name: Deploy NestJS via SSH

on:
  workflow_dispatch:

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start SSH via tmate
        uses: mxschmitt/action-tmate@v3
        with:
          ssh: true

      - name: Keep job alive
        run: sleep 3600
